name: cd

on:
  workflow_dispatch:
  push:
    tags: [ v-* ]

env:
  project-name: ${{ secrets.PROJECT_NAME }}

jobs:
  sam-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy
        run: sam deploy --stack-name ${{ env.project-name }}-prod
